//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace NutrientCalculator.SADService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="image", Namespace="http://schemas.datacontract.org/2004/07/sadServices")]
    public partial class image : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private string categoryField;
        
        private string descriptionField;
        
        private System.Guid guidField;
        
        private byte[] imageDataField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid guid {
            get {
                return this.guidField;
            }
            set {
                if ((this.guidField.Equals(value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] imageData {
            get {
                return this.imageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.imageDataField, value) != true)) {
                    this.imageDataField = value;
                    this.RaisePropertyChanged("imageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.latitudeField, value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.longitudeField, value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SADService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AddImage", ReplyAction="http://tempuri.org/IService1/AddImageResponse")]
        System.IAsyncResult BeginAddImage(System.Guid guid, byte[] sentImage, string lat, string longi, string description, string category, System.AsyncCallback callback, object asyncState);
        
        void EndAddImage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ViewImages", ReplyAction="http://tempuri.org/IService1/ViewImagesResponse")]
        System.IAsyncResult BeginViewImages(System.Guid guid, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> EndViewImages(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SearchImages", ReplyAction="http://tempuri.org/IService1/SearchImagesResponse")]
        System.IAsyncResult BeginSearchImages(System.Guid guid, string category, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> EndSearchImages(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSentiment", ReplyAction="http://tempuri.org/IService1/GetSentimentResponse")]
        System.IAsyncResult BeginGetSentiment(string tweetData, System.AsyncCallback callback, object asyncState);
        
        string EndGetSentiment(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetTop40", ReplyAction="http://tempuri.org/IService1/GetTop40Response")]
        System.IAsyncResult BeginGetTop40(System.AsyncCallback callback, object asyncState);
        
        string EndGetTop40(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetRandomSingle", ReplyAction="http://tempuri.org/IService1/GetRandomSingleResponse")]
        System.IAsyncResult BeginGetRandomSingle(System.AsyncCallback callback, object asyncState);
        
        string EndGetRandomSingle(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNumberOne", ReplyAction="http://tempuri.org/IService1/GetNumberOneResponse")]
        System.IAsyncResult BeginGetNumberOne(System.AsyncCallback callback, object asyncState);
        
        string EndGetNumberOne(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SearchMovies", ReplyAction="http://tempuri.org/IService1/SearchMoviesResponse")]
        System.IAsyncResult BeginSearchMovies(string movieQuery, System.AsyncCallback callback, object asyncState);
        
        string EndSearchMovies(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/discoverMovies", ReplyAction="http://tempuri.org/IService1/discoverMoviesResponse")]
        System.IAsyncResult BegindiscoverMovies(string genre, System.AsyncCallback callback, object asyncState);
        
        string EnddiscoverMovies(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/movieDetails", ReplyAction="http://tempuri.org/IService1/movieDetailsResponse")]
        System.IAsyncResult BeginmovieDetails(string movieID, System.AsyncCallback callback, object asyncState);
        
        string EndmovieDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetEnergyData", ReplyAction="http://tempuri.org/IService1/GetEnergyDataResponse")]
        System.IAsyncResult BeginGetEnergyData(string building, System.AsyncCallback callback, object asyncState);
        
        string EndGetEnergyData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetCrimeData", ReplyAction="http://tempuri.org/IService1/GetCrimeDataResponse")]
        System.IAsyncResult BeginGetCrimeData(double lat, double longi, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<int> EndGetCrimeData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : NutrientCalculator.SADService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewImagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ViewImagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchImagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchImagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSentimentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSentimentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTop40CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTop40CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRandomSingleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRandomSingleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNumberOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNumberOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchMoviesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchMoviesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class discoverMoviesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public discoverMoviesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class movieDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public movieDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEnergyDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEnergyDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCrimeDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCrimeDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<int> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<int>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<NutrientCalculator.SADService.IService1>, NutrientCalculator.SADService.IService1 {
        
        private BeginOperationDelegate onBeginAddImageDelegate;
        
        private EndOperationDelegate onEndAddImageDelegate;
        
        private System.Threading.SendOrPostCallback onAddImageCompletedDelegate;
        
        private BeginOperationDelegate onBeginViewImagesDelegate;
        
        private EndOperationDelegate onEndViewImagesDelegate;
        
        private System.Threading.SendOrPostCallback onViewImagesCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchImagesDelegate;
        
        private EndOperationDelegate onEndSearchImagesDelegate;
        
        private System.Threading.SendOrPostCallback onSearchImagesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSentimentDelegate;
        
        private EndOperationDelegate onEndGetSentimentDelegate;
        
        private System.Threading.SendOrPostCallback onGetSentimentCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTop40Delegate;
        
        private EndOperationDelegate onEndGetTop40Delegate;
        
        private System.Threading.SendOrPostCallback onGetTop40CompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRandomSingleDelegate;
        
        private EndOperationDelegate onEndGetRandomSingleDelegate;
        
        private System.Threading.SendOrPostCallback onGetRandomSingleCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNumberOneDelegate;
        
        private EndOperationDelegate onEndGetNumberOneDelegate;
        
        private System.Threading.SendOrPostCallback onGetNumberOneCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchMoviesDelegate;
        
        private EndOperationDelegate onEndSearchMoviesDelegate;
        
        private System.Threading.SendOrPostCallback onSearchMoviesCompletedDelegate;
        
        private BeginOperationDelegate onBegindiscoverMoviesDelegate;
        
        private EndOperationDelegate onEnddiscoverMoviesDelegate;
        
        private System.Threading.SendOrPostCallback ondiscoverMoviesCompletedDelegate;
        
        private BeginOperationDelegate onBeginmovieDetailsDelegate;
        
        private EndOperationDelegate onEndmovieDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onmovieDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEnergyDataDelegate;
        
        private EndOperationDelegate onEndGetEnergyDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetEnergyDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCrimeDataDelegate;
        
        private EndOperationDelegate onEndGetCrimeDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetCrimeDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddImageCompleted;
        
        public event System.EventHandler<ViewImagesCompletedEventArgs> ViewImagesCompleted;
        
        public event System.EventHandler<SearchImagesCompletedEventArgs> SearchImagesCompleted;
        
        public event System.EventHandler<GetSentimentCompletedEventArgs> GetSentimentCompleted;
        
        public event System.EventHandler<GetTop40CompletedEventArgs> GetTop40Completed;
        
        public event System.EventHandler<GetRandomSingleCompletedEventArgs> GetRandomSingleCompleted;
        
        public event System.EventHandler<GetNumberOneCompletedEventArgs> GetNumberOneCompleted;
        
        public event System.EventHandler<SearchMoviesCompletedEventArgs> SearchMoviesCompleted;
        
        public event System.EventHandler<discoverMoviesCompletedEventArgs> discoverMoviesCompleted;
        
        public event System.EventHandler<movieDetailsCompletedEventArgs> movieDetailsCompleted;
        
        public event System.EventHandler<GetEnergyDataCompletedEventArgs> GetEnergyDataCompleted;
        
        public event System.EventHandler<GetCrimeDataCompletedEventArgs> GetCrimeDataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginAddImage(System.Guid guid, byte[] sentImage, string lat, string longi, string description, string category, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddImage(guid, sentImage, lat, longi, description, category, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void NutrientCalculator.SADService.IService1.EndAddImage(System.IAsyncResult result) {
            base.Channel.EndAddImage(result);
        }
        
        private System.IAsyncResult OnBeginAddImage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid guid = ((System.Guid)(inValues[0]));
            byte[] sentImage = ((byte[])(inValues[1]));
            string lat = ((string)(inValues[2]));
            string longi = ((string)(inValues[3]));
            string description = ((string)(inValues[4]));
            string category = ((string)(inValues[5]));
            return ((NutrientCalculator.SADService.IService1)(this)).BeginAddImage(guid, sentImage, lat, longi, description, category, callback, asyncState);
        }
        
        private object[] OnEndAddImage(System.IAsyncResult result) {
            ((NutrientCalculator.SADService.IService1)(this)).EndAddImage(result);
            return null;
        }
        
        private void OnAddImageCompleted(object state) {
            if ((this.AddImageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddImageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddImageAsync(System.Guid guid, byte[] sentImage, string lat, string longi, string description, string category) {
            this.AddImageAsync(guid, sentImage, lat, longi, description, category, null);
        }
        
        public void AddImageAsync(System.Guid guid, byte[] sentImage, string lat, string longi, string description, string category, object userState) {
            if ((this.onBeginAddImageDelegate == null)) {
                this.onBeginAddImageDelegate = new BeginOperationDelegate(this.OnBeginAddImage);
            }
            if ((this.onEndAddImageDelegate == null)) {
                this.onEndAddImageDelegate = new EndOperationDelegate(this.OnEndAddImage);
            }
            if ((this.onAddImageCompletedDelegate == null)) {
                this.onAddImageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddImageCompleted);
            }
            base.InvokeAsync(this.onBeginAddImageDelegate, new object[] {
                        guid,
                        sentImage,
                        lat,
                        longi,
                        description,
                        category}, this.onEndAddImageDelegate, this.onAddImageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginViewImages(System.Guid guid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginViewImages(guid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> NutrientCalculator.SADService.IService1.EndViewImages(System.IAsyncResult result) {
            return base.Channel.EndViewImages(result);
        }
        
        private System.IAsyncResult OnBeginViewImages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid guid = ((System.Guid)(inValues[0]));
            return ((NutrientCalculator.SADService.IService1)(this)).BeginViewImages(guid, callback, asyncState);
        }
        
        private object[] OnEndViewImages(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> retVal = ((NutrientCalculator.SADService.IService1)(this)).EndViewImages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnViewImagesCompleted(object state) {
            if ((this.ViewImagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ViewImagesCompleted(this, new ViewImagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ViewImagesAsync(System.Guid guid) {
            this.ViewImagesAsync(guid, null);
        }
        
        public void ViewImagesAsync(System.Guid guid, object userState) {
            if ((this.onBeginViewImagesDelegate == null)) {
                this.onBeginViewImagesDelegate = new BeginOperationDelegate(this.OnBeginViewImages);
            }
            if ((this.onEndViewImagesDelegate == null)) {
                this.onEndViewImagesDelegate = new EndOperationDelegate(this.OnEndViewImages);
            }
            if ((this.onViewImagesCompletedDelegate == null)) {
                this.onViewImagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnViewImagesCompleted);
            }
            base.InvokeAsync(this.onBeginViewImagesDelegate, new object[] {
                        guid}, this.onEndViewImagesDelegate, this.onViewImagesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginSearchImages(System.Guid guid, string category, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchImages(guid, category, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> NutrientCalculator.SADService.IService1.EndSearchImages(System.IAsyncResult result) {
            return base.Channel.EndSearchImages(result);
        }
        
        private System.IAsyncResult OnBeginSearchImages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid guid = ((System.Guid)(inValues[0]));
            string category = ((string)(inValues[1]));
            return ((NutrientCalculator.SADService.IService1)(this)).BeginSearchImages(guid, category, callback, asyncState);
        }
        
        private object[] OnEndSearchImages(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> retVal = ((NutrientCalculator.SADService.IService1)(this)).EndSearchImages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchImagesCompleted(object state) {
            if ((this.SearchImagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchImagesCompleted(this, new SearchImagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchImagesAsync(System.Guid guid, string category) {
            this.SearchImagesAsync(guid, category, null);
        }
        
        public void SearchImagesAsync(System.Guid guid, string category, object userState) {
            if ((this.onBeginSearchImagesDelegate == null)) {
                this.onBeginSearchImagesDelegate = new BeginOperationDelegate(this.OnBeginSearchImages);
            }
            if ((this.onEndSearchImagesDelegate == null)) {
                this.onEndSearchImagesDelegate = new EndOperationDelegate(this.OnEndSearchImages);
            }
            if ((this.onSearchImagesCompletedDelegate == null)) {
                this.onSearchImagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchImagesCompleted);
            }
            base.InvokeAsync(this.onBeginSearchImagesDelegate, new object[] {
                        guid,
                        category}, this.onEndSearchImagesDelegate, this.onSearchImagesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginGetSentiment(string tweetData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSentiment(tweetData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NutrientCalculator.SADService.IService1.EndGetSentiment(System.IAsyncResult result) {
            return base.Channel.EndGetSentiment(result);
        }
        
        private System.IAsyncResult OnBeginGetSentiment(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string tweetData = ((string)(inValues[0]));
            return ((NutrientCalculator.SADService.IService1)(this)).BeginGetSentiment(tweetData, callback, asyncState);
        }
        
        private object[] OnEndGetSentiment(System.IAsyncResult result) {
            string retVal = ((NutrientCalculator.SADService.IService1)(this)).EndGetSentiment(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSentimentCompleted(object state) {
            if ((this.GetSentimentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSentimentCompleted(this, new GetSentimentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSentimentAsync(string tweetData) {
            this.GetSentimentAsync(tweetData, null);
        }
        
        public void GetSentimentAsync(string tweetData, object userState) {
            if ((this.onBeginGetSentimentDelegate == null)) {
                this.onBeginGetSentimentDelegate = new BeginOperationDelegate(this.OnBeginGetSentiment);
            }
            if ((this.onEndGetSentimentDelegate == null)) {
                this.onEndGetSentimentDelegate = new EndOperationDelegate(this.OnEndGetSentiment);
            }
            if ((this.onGetSentimentCompletedDelegate == null)) {
                this.onGetSentimentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSentimentCompleted);
            }
            base.InvokeAsync(this.onBeginGetSentimentDelegate, new object[] {
                        tweetData}, this.onEndGetSentimentDelegate, this.onGetSentimentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginGetTop40(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTop40(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NutrientCalculator.SADService.IService1.EndGetTop40(System.IAsyncResult result) {
            return base.Channel.EndGetTop40(result);
        }
        
        private System.IAsyncResult OnBeginGetTop40(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((NutrientCalculator.SADService.IService1)(this)).BeginGetTop40(callback, asyncState);
        }
        
        private object[] OnEndGetTop40(System.IAsyncResult result) {
            string retVal = ((NutrientCalculator.SADService.IService1)(this)).EndGetTop40(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTop40Completed(object state) {
            if ((this.GetTop40Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTop40Completed(this, new GetTop40CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTop40Async() {
            this.GetTop40Async(null);
        }
        
        public void GetTop40Async(object userState) {
            if ((this.onBeginGetTop40Delegate == null)) {
                this.onBeginGetTop40Delegate = new BeginOperationDelegate(this.OnBeginGetTop40);
            }
            if ((this.onEndGetTop40Delegate == null)) {
                this.onEndGetTop40Delegate = new EndOperationDelegate(this.OnEndGetTop40);
            }
            if ((this.onGetTop40CompletedDelegate == null)) {
                this.onGetTop40CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTop40Completed);
            }
            base.InvokeAsync(this.onBeginGetTop40Delegate, null, this.onEndGetTop40Delegate, this.onGetTop40CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginGetRandomSingle(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRandomSingle(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NutrientCalculator.SADService.IService1.EndGetRandomSingle(System.IAsyncResult result) {
            return base.Channel.EndGetRandomSingle(result);
        }
        
        private System.IAsyncResult OnBeginGetRandomSingle(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((NutrientCalculator.SADService.IService1)(this)).BeginGetRandomSingle(callback, asyncState);
        }
        
        private object[] OnEndGetRandomSingle(System.IAsyncResult result) {
            string retVal = ((NutrientCalculator.SADService.IService1)(this)).EndGetRandomSingle(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRandomSingleCompleted(object state) {
            if ((this.GetRandomSingleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRandomSingleCompleted(this, new GetRandomSingleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRandomSingleAsync() {
            this.GetRandomSingleAsync(null);
        }
        
        public void GetRandomSingleAsync(object userState) {
            if ((this.onBeginGetRandomSingleDelegate == null)) {
                this.onBeginGetRandomSingleDelegate = new BeginOperationDelegate(this.OnBeginGetRandomSingle);
            }
            if ((this.onEndGetRandomSingleDelegate == null)) {
                this.onEndGetRandomSingleDelegate = new EndOperationDelegate(this.OnEndGetRandomSingle);
            }
            if ((this.onGetRandomSingleCompletedDelegate == null)) {
                this.onGetRandomSingleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRandomSingleCompleted);
            }
            base.InvokeAsync(this.onBeginGetRandomSingleDelegate, null, this.onEndGetRandomSingleDelegate, this.onGetRandomSingleCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginGetNumberOne(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNumberOne(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NutrientCalculator.SADService.IService1.EndGetNumberOne(System.IAsyncResult result) {
            return base.Channel.EndGetNumberOne(result);
        }
        
        private System.IAsyncResult OnBeginGetNumberOne(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((NutrientCalculator.SADService.IService1)(this)).BeginGetNumberOne(callback, asyncState);
        }
        
        private object[] OnEndGetNumberOne(System.IAsyncResult result) {
            string retVal = ((NutrientCalculator.SADService.IService1)(this)).EndGetNumberOne(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNumberOneCompleted(object state) {
            if ((this.GetNumberOneCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNumberOneCompleted(this, new GetNumberOneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNumberOneAsync() {
            this.GetNumberOneAsync(null);
        }
        
        public void GetNumberOneAsync(object userState) {
            if ((this.onBeginGetNumberOneDelegate == null)) {
                this.onBeginGetNumberOneDelegate = new BeginOperationDelegate(this.OnBeginGetNumberOne);
            }
            if ((this.onEndGetNumberOneDelegate == null)) {
                this.onEndGetNumberOneDelegate = new EndOperationDelegate(this.OnEndGetNumberOne);
            }
            if ((this.onGetNumberOneCompletedDelegate == null)) {
                this.onGetNumberOneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNumberOneCompleted);
            }
            base.InvokeAsync(this.onBeginGetNumberOneDelegate, null, this.onEndGetNumberOneDelegate, this.onGetNumberOneCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginSearchMovies(string movieQuery, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchMovies(movieQuery, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NutrientCalculator.SADService.IService1.EndSearchMovies(System.IAsyncResult result) {
            return base.Channel.EndSearchMovies(result);
        }
        
        private System.IAsyncResult OnBeginSearchMovies(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string movieQuery = ((string)(inValues[0]));
            return ((NutrientCalculator.SADService.IService1)(this)).BeginSearchMovies(movieQuery, callback, asyncState);
        }
        
        private object[] OnEndSearchMovies(System.IAsyncResult result) {
            string retVal = ((NutrientCalculator.SADService.IService1)(this)).EndSearchMovies(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchMoviesCompleted(object state) {
            if ((this.SearchMoviesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchMoviesCompleted(this, new SearchMoviesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchMoviesAsync(string movieQuery) {
            this.SearchMoviesAsync(movieQuery, null);
        }
        
        public void SearchMoviesAsync(string movieQuery, object userState) {
            if ((this.onBeginSearchMoviesDelegate == null)) {
                this.onBeginSearchMoviesDelegate = new BeginOperationDelegate(this.OnBeginSearchMovies);
            }
            if ((this.onEndSearchMoviesDelegate == null)) {
                this.onEndSearchMoviesDelegate = new EndOperationDelegate(this.OnEndSearchMovies);
            }
            if ((this.onSearchMoviesCompletedDelegate == null)) {
                this.onSearchMoviesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchMoviesCompleted);
            }
            base.InvokeAsync(this.onBeginSearchMoviesDelegate, new object[] {
                        movieQuery}, this.onEndSearchMoviesDelegate, this.onSearchMoviesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BegindiscoverMovies(string genre, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindiscoverMovies(genre, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NutrientCalculator.SADService.IService1.EnddiscoverMovies(System.IAsyncResult result) {
            return base.Channel.EnddiscoverMovies(result);
        }
        
        private System.IAsyncResult OnBegindiscoverMovies(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string genre = ((string)(inValues[0]));
            return ((NutrientCalculator.SADService.IService1)(this)).BegindiscoverMovies(genre, callback, asyncState);
        }
        
        private object[] OnEnddiscoverMovies(System.IAsyncResult result) {
            string retVal = ((NutrientCalculator.SADService.IService1)(this)).EnddiscoverMovies(result);
            return new object[] {
                    retVal};
        }
        
        private void OndiscoverMoviesCompleted(object state) {
            if ((this.discoverMoviesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.discoverMoviesCompleted(this, new discoverMoviesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void discoverMoviesAsync(string genre) {
            this.discoverMoviesAsync(genre, null);
        }
        
        public void discoverMoviesAsync(string genre, object userState) {
            if ((this.onBegindiscoverMoviesDelegate == null)) {
                this.onBegindiscoverMoviesDelegate = new BeginOperationDelegate(this.OnBegindiscoverMovies);
            }
            if ((this.onEnddiscoverMoviesDelegate == null)) {
                this.onEnddiscoverMoviesDelegate = new EndOperationDelegate(this.OnEnddiscoverMovies);
            }
            if ((this.ondiscoverMoviesCompletedDelegate == null)) {
                this.ondiscoverMoviesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndiscoverMoviesCompleted);
            }
            base.InvokeAsync(this.onBegindiscoverMoviesDelegate, new object[] {
                        genre}, this.onEnddiscoverMoviesDelegate, this.ondiscoverMoviesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginmovieDetails(string movieID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginmovieDetails(movieID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NutrientCalculator.SADService.IService1.EndmovieDetails(System.IAsyncResult result) {
            return base.Channel.EndmovieDetails(result);
        }
        
        private System.IAsyncResult OnBeginmovieDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string movieID = ((string)(inValues[0]));
            return ((NutrientCalculator.SADService.IService1)(this)).BeginmovieDetails(movieID, callback, asyncState);
        }
        
        private object[] OnEndmovieDetails(System.IAsyncResult result) {
            string retVal = ((NutrientCalculator.SADService.IService1)(this)).EndmovieDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnmovieDetailsCompleted(object state) {
            if ((this.movieDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.movieDetailsCompleted(this, new movieDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void movieDetailsAsync(string movieID) {
            this.movieDetailsAsync(movieID, null);
        }
        
        public void movieDetailsAsync(string movieID, object userState) {
            if ((this.onBeginmovieDetailsDelegate == null)) {
                this.onBeginmovieDetailsDelegate = new BeginOperationDelegate(this.OnBeginmovieDetails);
            }
            if ((this.onEndmovieDetailsDelegate == null)) {
                this.onEndmovieDetailsDelegate = new EndOperationDelegate(this.OnEndmovieDetails);
            }
            if ((this.onmovieDetailsCompletedDelegate == null)) {
                this.onmovieDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnmovieDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginmovieDetailsDelegate, new object[] {
                        movieID}, this.onEndmovieDetailsDelegate, this.onmovieDetailsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginGetEnergyData(string building, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEnergyData(building, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NutrientCalculator.SADService.IService1.EndGetEnergyData(System.IAsyncResult result) {
            return base.Channel.EndGetEnergyData(result);
        }
        
        private System.IAsyncResult OnBeginGetEnergyData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string building = ((string)(inValues[0]));
            return ((NutrientCalculator.SADService.IService1)(this)).BeginGetEnergyData(building, callback, asyncState);
        }
        
        private object[] OnEndGetEnergyData(System.IAsyncResult result) {
            string retVal = ((NutrientCalculator.SADService.IService1)(this)).EndGetEnergyData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEnergyDataCompleted(object state) {
            if ((this.GetEnergyDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEnergyDataCompleted(this, new GetEnergyDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEnergyDataAsync(string building) {
            this.GetEnergyDataAsync(building, null);
        }
        
        public void GetEnergyDataAsync(string building, object userState) {
            if ((this.onBeginGetEnergyDataDelegate == null)) {
                this.onBeginGetEnergyDataDelegate = new BeginOperationDelegate(this.OnBeginGetEnergyData);
            }
            if ((this.onEndGetEnergyDataDelegate == null)) {
                this.onEndGetEnergyDataDelegate = new EndOperationDelegate(this.OnEndGetEnergyData);
            }
            if ((this.onGetEnergyDataCompletedDelegate == null)) {
                this.onGetEnergyDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEnergyDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetEnergyDataDelegate, new object[] {
                        building}, this.onEndGetEnergyDataDelegate, this.onGetEnergyDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NutrientCalculator.SADService.IService1.BeginGetCrimeData(double lat, double longi, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCrimeData(lat, longi, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<int> NutrientCalculator.SADService.IService1.EndGetCrimeData(System.IAsyncResult result) {
            return base.Channel.EndGetCrimeData(result);
        }
        
        private System.IAsyncResult OnBeginGetCrimeData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double lat = ((double)(inValues[0]));
            double longi = ((double)(inValues[1]));
            return ((NutrientCalculator.SADService.IService1)(this)).BeginGetCrimeData(lat, longi, callback, asyncState);
        }
        
        private object[] OnEndGetCrimeData(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<int> retVal = ((NutrientCalculator.SADService.IService1)(this)).EndGetCrimeData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCrimeDataCompleted(object state) {
            if ((this.GetCrimeDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCrimeDataCompleted(this, new GetCrimeDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCrimeDataAsync(double lat, double longi) {
            this.GetCrimeDataAsync(lat, longi, null);
        }
        
        public void GetCrimeDataAsync(double lat, double longi, object userState) {
            if ((this.onBeginGetCrimeDataDelegate == null)) {
                this.onBeginGetCrimeDataDelegate = new BeginOperationDelegate(this.OnBeginGetCrimeData);
            }
            if ((this.onEndGetCrimeDataDelegate == null)) {
                this.onEndGetCrimeDataDelegate = new EndOperationDelegate(this.OnEndGetCrimeData);
            }
            if ((this.onGetCrimeDataCompletedDelegate == null)) {
                this.onGetCrimeDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCrimeDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetCrimeDataDelegate, new object[] {
                        lat,
                        longi}, this.onEndGetCrimeDataDelegate, this.onGetCrimeDataCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override NutrientCalculator.SADService.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<NutrientCalculator.SADService.IService1>, NutrientCalculator.SADService.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<NutrientCalculator.SADService.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAddImage(System.Guid guid, byte[] sentImage, string lat, string longi, string description, string category, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = guid;
                _args[1] = sentImage;
                _args[2] = lat;
                _args[3] = longi;
                _args[4] = description;
                _args[5] = category;
                System.IAsyncResult _result = base.BeginInvoke("AddImage", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddImage(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddImage", _args, result);
            }
            
            public System.IAsyncResult BeginViewImages(System.Guid guid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = guid;
                System.IAsyncResult _result = base.BeginInvoke("ViewImages", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> EndViewImages(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> _result = ((System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image>)(base.EndInvoke("ViewImages", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSearchImages(System.Guid guid, string category, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = guid;
                _args[1] = category;
                System.IAsyncResult _result = base.BeginInvoke("SearchImages", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> EndSearchImages(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image> _result = ((System.Collections.ObjectModel.ObservableCollection<NutrientCalculator.SADService.image>)(base.EndInvoke("SearchImages", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSentiment(string tweetData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = tweetData;
                System.IAsyncResult _result = base.BeginInvoke("GetSentiment", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetSentiment(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetSentiment", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTop40(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTop40", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetTop40(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetTop40", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRandomSingle(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetRandomSingle", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetRandomSingle(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetRandomSingle", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNumberOne(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetNumberOne", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetNumberOne(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetNumberOne", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSearchMovies(string movieQuery, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = movieQuery;
                System.IAsyncResult _result = base.BeginInvoke("SearchMovies", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSearchMovies(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("SearchMovies", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegindiscoverMovies(string genre, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = genre;
                System.IAsyncResult _result = base.BeginInvoke("discoverMovies", _args, callback, asyncState);
                return _result;
            }
            
            public string EnddiscoverMovies(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("discoverMovies", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginmovieDetails(string movieID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = movieID;
                System.IAsyncResult _result = base.BeginInvoke("movieDetails", _args, callback, asyncState);
                return _result;
            }
            
            public string EndmovieDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("movieDetails", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetEnergyData(string building, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = building;
                System.IAsyncResult _result = base.BeginInvoke("GetEnergyData", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetEnergyData(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetEnergyData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCrimeData(double lat, double longi, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = lat;
                _args[1] = longi;
                System.IAsyncResult _result = base.BeginInvoke("GetCrimeData", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<int> EndGetCrimeData(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<int> _result = ((System.Collections.ObjectModel.ObservableCollection<int>)(base.EndInvoke("GetCrimeData", _args, result)));
                return _result;
            }
        }
    }
}
